### ISSUE TITLE
Can't get exact error details from ExpoException

### ISSUE THREAD

**Issue by BennySpaghetti** [Alymosul/exponent-server-sdk-php#31] opened 2019-02-28 15:46 UTC
The doc page for expo's push notifications lists four kinds of error to be returned from the service, `DeviceNotRegistered, MessageTooBig, MessageRateExceeded, and InvalidCredentials`, but the ExpoException class doesn't provide a proper way to detect these, it only exposes the error message. 

I'd rather not be regexping through the error messages; would you be able to add a way to retrieve this detail from the exception object? https://docs.expo.io/versions/latest/guides/push-notifications/#receipt-response-format

**Comment by Alymosul** [comment] 2019-05-06 14:01
👍 for that, I'll try to add these exceptions to the package soon! Feel free to submit the change through a PR, it's always welcome to help :)

**Comment by Ahc45** [comment] 2020-12-12 05:31
Type: ExponentPhpSDK\Exceptions\UnexpectedResponseException

Message: Unexpected response was received from Expo API.
I have this error. I tried using Codeigniter.

**Comment by rehmankhalil1001** [comment] 2021-02-02 12:33
@Alymosul 

> ExponentPhpSDK\Exceptions\UnexpectedResponseException Object
(
    [message:protected] => Unexpected response was received from Expo API.
    [string:Exception:private] => 
    [code:protected] => 500
    [file:protected] => /home/example/public_html/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php
    [line:protected] => 206
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/example.com/public_html/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php
                    [line] => 112
                    [function] => executeCurl
                    [class] => ExponentPhpSDK\Expo
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Resource id #8
                        )
                )
            [1] => Array
                (
                    [file] => /home/example.com/public_html/application/controllers/Main.php
                    [line] => 199
                    [function] => notify
                    [class] => ExponentPhpSDK\Expo
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => service_requests_8
                                )
                            [1] => Array
                                (
                                    [title] => Service Requested
                                    [body] => das
                                    [data] => {"notification_type":"service_requested"}
                                )
                        )
                )
            [2] => Array
                (
                    [file] => /home/example.com/public_html/system/core/CodeIgniter.php
                    [line] => 532
                    [function] => privacy_policy
                    [class] => Main
                    [type] => ->
                    [args] => Array
                        (
                        )
                )
            [3] => Array
                (
                    [file] => /home/example.com/public_html/index.php
                    [line] => 318
                    [args] => Array
                        (
                            [0] => /home/example.com/public_html/system/core/CodeIgniter.php
                        )
                    [function] => require_once
                )
        )
    [previous:Exception:private] => 
)

  receiving this error, this was working fine previously not sure what went wrong after the last build. 
  
  Since i am using FCM i have also run the command:
  
  

> expo push:android:upload --api-key <server-key>

this was uploaded successfully, not sure what the issue is, is this Firebase related ? i have tried the push notification tool and it is sending notifications 

My PHP codeigniter code:

`
try {
            $channelName = 'service_requests_8';

            $recipient= "ExponentPushToken[XYZXYZXYXX]";//

            // You can quickly bootup an expo instance
            $expo = \ExponentPhpSDK\Expo::normalSetup();

            // Subscribe the recipient to the server

            // Build the notification data
            $notification = ['title' => 'Service Requested','body' => "das",'data'=>json_encode(array('notification_type'=>'service_requested'))];

            // Notify an interest with a notification
            $expo->subscribe($channelName, $recipient);
            $expo->notify($channelName, $notification);
        } catch (Exception $e) {
            print_r($e);
        }
`

Any help?

**Comment by rodolfobarretoweb** [comment] 2021-03-02 17:51
Hi everyone! I just did a pull request resolving this problem

https://github.com/Alymosul/exponent-server-sdk-php/pull/64

**Comment by giolukiao** [comment] 2021-11-04 22:00
> Type: ExponentPhpSDK\Exceptions\UnexpectedResponseException
> 
> Message: Unexpected response was received from Expo API. I have this error. I tried using Codeigniter.

hello you can solution it?

**Comment by BizworksBizpay** [comment] 2021-12-14 15:13
> > Type: ExponentPhpSDK\Exceptions\UnexpectedResponseException
> > Message: Unexpected response was received from Expo API. I have this error. I tried using Codeigniter.
> 
> hello you can solution it?

i solved this problem, This problem occurs when SSL is not configured
Your php.ini should be set

﻿https://curl.se/docs/caextract.html
You can download it here and fill in the path.

[curl]
curl.cainfo ="Your php path/PHP/v7.4/extras/ssl/cacert.pem"
[openssl]
openssl.cafile="Your php path/PHP/v7.4/extras/ssl/cacert.pem"

after restarting apache ,then try again
:)

**Comment by josephajibodu** [comment] 2022-02-08 16:28
This issue should be closed

**Closed as completed** 2022-02-08 16:40 UTC
